### PR TITLE
I170 user delete bug fix

### LINKED ISSUE #170: User törlése után a naptár nem jelenít meg eseményeket
A törölt user nem törlődik a korábban mentett meetingekből (létrehozó vagy meghívottak listájából), így a back-end hibát dob a meetingek kilistázásakor és naptárnézetben mejelenítéskor is.

> **".EntityNotFoundException: Unable to find hu.flowacademy.companycalendar.model.User with id"**

### PR DESCRIPTION
**Pull request by urbanjozsef88**
#170

### CODE REVIEW

File: eta-company-calendar-backend/src/main/java/hu/flowacademy/companycalendar/repository/MeetingRepository.java [hunk 1]
```diff
@@ -24,6 +24,9 @@
           + "Meeting m LEFT OUTER JOIN m.requiredAttendants r LEFT OUTER JOIN m.optionalAttendants o "
           + "WHERE m.createdBy.id = ?1 OR r.id = ?1 OR o.id = ?1")
   List<Meeting> findByInvitedUserId(Long userId);
+
+  @Query("SELECT m FROM Meeting m where m.createdBy.id = ?1")
+  List<Meeting> findMeetingCreatedBy(Long userId);
```
Comment (borosr) [inline eta-company-calendar-backend/src/main/java/hu/flowacademy/companycalendar/repository/MeetingRepository.java]: Nem kell `@Query` inkább method based old meg: `findByCreatedBy_Id(Long userId)`
